# Armazena configurações não sensíveis que são injetadas como variáveis de ambiente no pod.
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-config
data:
  MESSAGE: {{ .Values.config.MESSAGE | quote }}