apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: devops-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: CUSTOM_MESSAGE
              value: "{{ .Values.env.CUSTOM_MESSAGE }}"
            - name: CONFIG_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: devops-config
                  key: MESSAGE
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devops-secret
                  key: PASSWORD
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
