# Armazena dados sensíveis (como senhas, tokens) que são injetados de forma segura nos containers.
apiVersion: v1
kind: Secret
metadata:
  name: devops-secret
type: Opaque
data:
  PASSWORD: {{ .Values.secret.PASSWORD }}
